### ISSUE TITLE
[Bug] Theme switches to light even when dark is set

### ISSUE THREAD

**Issue by qx-775** [maxmilton/new-tab#1339] opened 2021-12-16 16:09 UTC
At random times new tab shows a white background as if the light theme was set. However it says dark theme is in use in the settings.

This is really annoying since it hurts my eyes haha. I don't know why or when this happens but perhaps someone else has had it too?

Version: 0.18, not from chrome webstore but self build using npm build

**Comment by maxmilton** [comment] 2021-12-18 20:33
Thanks for the bug report. I've got a few questions to try to narrow down the cause:

1. Is it FOUC (flash of unstyled content), where the page is white but just for a moment? Or is it persistent?
2. If it's FOUC, is there anything that might be slowing down the initial page load? Are there some other extensions that load first? Is it a slow system and/or a slow HHD?
3. If it's persistent, does the theme load properly when you refresh the page? 
4. Is it the light theme or the base styles without a theme?

---

I'm the same as you and prefer a dark theme. Anything white hurts the eyes when browsing at night! Especially sudden unexpected flashes.

It used to happen before where when loading the page it would flash white first before the theme was loaded. More recently I rewrote the theme loader to be synchronous and to load the theme before the page is actually rendered.

Under the hood, the way it currently works is there's a base set of styles that make up most of the CSS. These base styles are inline in the HTML so they will always load regardless. Then there are the themes which are small CSS that set some variables (CSS custom properties) and provide minor tweaks. The user's chosen theme is loaded into `localStorage` when the theme is changed in the settings or when the extension is updated. On a new tab page load we get the theme from `localStorage` and inject it into a `<style>` tag.

This theme loading strategy is a bit complex since a theme needs to be pre-loaded and then injected, but it does allow for a lot of power around theming. User customisable themes would be possible for example (it's not a feature now but something I'd like to add in future).

**Comment by qx-775** [comment] 2021-12-24 09:12
1. It is persistent among other tabs and when i close the browser.
2. There is no page slowdown
3. When I refresh the page the theme does not load properly and just stay on light theme while the settings clearly say dark theme.
4. For now I can't clearly see the difference between light and without style. 
5. It persists across reloads, browser restarts or when i open up a new tab.

For now I will update to the latest git commit to see if the issue persists. Will close after 30 days if it's gone.

**Comment by maxmilton** [comment] 2021-12-29 06:20
Thank you for the info :slightly_smiling_face: 

I ran into what might be the same issue and fixed it in #1349. Although what you reported may be a different issue, since you mentioned the light theme is being loaded instead of your chosen theme (and not "no theme"). Closing the issue for now as there's a chance the bug is fixed, but please reopen if you encounter it again.

---

The bug I saw was in essence a race condition between the browser's HTML parser + DOM constructor, and inserting `textContent` into the theme `<style>` node. This extension omits all unnecessary tags in `newtab.html`, so the browser adds any implicit standard HTML tags automatically. If that happened at exactly the same time as setting the style node `textContent`, it inserted text into unexpected parts of the document, breaking the DOM and theme. This could cause page to load with "no theme".

The fix creates the a style node and inserts it in the DOM dynamically, which should prevent the race condition. The theme loader is a little larger but overall the performance is actually better!

**Comment by maxmilton** [comment] 2022-01-09 01:56
I'm reopening the issue as I've observed the same thing happening. My fix didn't work as expected.

**Comment by maxmilton** [comment] 2024-07-16 02:50
I haven't run into this issue in a long time so I'm going to consider it fixed. There have been various improvements to theme loading since this issue was created including a complete overhaul of how the themes work internally.

Additionally, the latest release has a bunch of theme changes including an auto light/dark theme by default <https://github.com/maxmilton/new-tab/releases/tag/v0.23.0>. It's been submitted to the [Chrome Webstore](https://chrome.google.com/webstore/detail/new-tab/cpcibnbdmpmcmnkhoiilpnlaepkepknb) and once approved it will roll out to users.

**Closed by maxmilton** 2024-07-16 02:50 UTC
Labels: bug
